FROM nginx:1.15.7

# RUN apt-get update && apt-get install -y \
#     wget

# RUN mkdir -p /var/www/html \
#     && cd /var/www/html/ \
#     wget -O modx.tar.gz https://github.com/modxcms/revolution/archive/v2.7.0-pl.tar.gz 